version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: restaurant_queue

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6001:6001"
    environment:
      MONGO_URI: mongodb://mongo:27017/restaurant_queue
      JWT_SECRET: replace_in_production
      FLASK_ENV: development
      PORT: 6001
      CORS_ORIGINS: http://localhost:8082,http://127.0.0.1:8082,http://192.168.0.111:8082
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

volumes:
  mongo_data:
